--Description of tables

--USERS (
--	id integer generated by default as identity, 
--	phone varchar(255), 
--	username varchar(255))

-- MEETINGS (
--	id integer generated by default as identity,
--	address varchar(255),
--	date date,
--	latitude float,
--	longitude float, 
-- 	title varchar(255),
--	moc integer)

-- GUESTS (
--	meeting_id integer not null, 
--	user_id integer not null)

-- PARTICIPANTS (
--	meeting_id integer not null,
--	user_id integer not null)

-- LOCATIONS (
--	id integer generated by default as identity,
--	date date, 
--	latitude float, 
--	longitude float, 
--	user integer)

-- First scenario
-- Luca, for his birthday, has invited Mario and Peppe to eat a pizza  
-- in Torre Annunziata on March 15th 2013 at 20:30  
-- Giovanni has been invited too, but he was busy with studies so he decided not to participate
-- Mario at 19:45 is in Naples, at 20:00 is on the highway
-- Giuseppe at 20:00 is in Sant'agnello, at 20:15 is still in Sant'Agnello
-- Luca at 20:00 is in Torre Annunziata, at 20:15 is still in Torre Annunziata
-- Meeting coordinates: 40° 45.475', 14° 26.354' (40.75791666666667, 14.439233333333334)
-- Highway coordinates: 40° 48.544', 14° 21.770' (40.809066666666666, 14.362833333333333)
-- Torre Annunziata coodinates: 40° 45.473', 14° 26.367' (40.75788333333333, 14.43945)
-- Naples coordinates: 40° 49.092', 14° 10.764' (40.8182, 14.1794)
-- Sant'Agnello coordinates: 40° 37.904', 14° 23.912' (40.63173333333334, 14.398533333333333)
insert into users(id,username,phone) values (1,'peppe','3391421288');
insert into users(id,username,phone) values (2,'mario','3490838036');
insert into users(id,username,phone) values (3,'luca','3201522887');
insert into users(id,username,phone) values (4,'giovanni','3733912057');

insert into meetings(id,title,address,date,latitude,longitude,moc) values (1,'Pizza for Luca birthday', 'Corso Umberto I, 274', parsedatetime('15-03-2013 20:30', 'dd-MM-yyyy hh:mm'), 40.75791666666667, 14.439233333333334, 3);

insert into guests values (1,1);
insert into guests values (1,2);
insert into guests values (1,3);
insert into guests values (1,4);

insert into participants values (1,1);
insert into participants values (1,2);
insert into participants values (1,3);

insert into locations(id,date,latitude,longitude,user) values (0,parsedatetime('15-03-2013 19:45', 'dd-MM-yyyy hh:mm'),40.8182,14.1794,2);
insert into locations(id,date,latitude,longitude,user) values (1,parsedatetime('15-03-2013 20:00', 'dd-MM-yyyy hh:mm'),40.809066666666666,14.362833333333333,2);
insert into locations(id,date,latitude,longitude,user) values (2,parsedatetime('15-03-2013 20:00', 'dd-MM-yyyy hh:mm'),40.63173333333334, 14.398533333333333,1);
insert into locations(id,date,latitude,longitude,user) values (3,parsedatetime('15-03-2013 20:15', 'dd-MM-yyyy hh:mm'),40.63173333333334, 14.398533333333333,1);
insert into locations(id,date,latitude,longitude,user) values (4,parsedatetime('15-03-2013 20:00', 'dd-MM-yyyy hh:mm'),40.75788333333333, 14.43945,3);
insert into locations(id,date,latitude,longitude,user) values (5,parsedatetime('15-03-2013 20:15', 'dd-MM-yyyy hh:mm'),40.75788333333333, 14.43945,3);



